#!/usr/bin/env node

/**
 * Setup script to automatically populate .env.local with deployed contract addresses
 * Usage: node scripts/setup-env.js
 */

const fs = require('fs');
const path = require('path');

// Read deployment addresses from Hardhat deployments
const deploymentsPath = path.join(__dirname, '../../deployments/localhost');

const contractNames = {
  'BugBountyProgram.json': 'BUG_BOUNTY_PROGRAM',
  'BountyVault.json': 'BOUNTY_VAULT',
  'ConfidentialPayouts.json': 'CONFIDENTIAL_PAYOUTS',
  'BugBountyMerkleTree.json': 'MERKLE_TREE',
  'BountyClaimVerifier.json': 'VERIFIER',
  'WhitehatReputation.json': 'WHITEHAT_REPUTATION',
  'DisputeResolver.json': 'DISPUTE_RESOLVER',
  'ProgramRegistry.json': 'PROGRAM_REGISTRY',
  'MockConfidentialUSDT.json': 'MOCK_USDT',
};

async function setupEnv() {
  console.log('🔧 Setting up .env.local with deployed contract addresses...\n');

  let envContent = `# Auto-generated by setup-env.js
# Generated at: ${new Date().toISOString()}

# Network Configuration
NEXT_PUBLIC_RPC_URL=http://127.0.0.1:8545
NEXT_PUBLIC_CHAIN_ID=31337

# Contract Addresses
`;

  // Check if deployments directory exists
  if (!fs.existsSync(deploymentsPath)) {
    console.error(`❌ Deployments directory not found: ${deploymentsPath}`);
    console.error('   Please deploy contracts first using: npm run deploy');
    process.exit(1);
  }

  let foundContracts = 0;

  // Read each contract deployment file
  for (const [filename, envVarName] of Object.entries(contractNames)) {
    const filePath = path.join(deploymentsPath, filename);
    
    if (fs.existsSync(filePath)) {
      try {
        const deployment = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        const address = deployment.address;
        
        if (address) {
          envContent += `NEXT_PUBLIC_${envVarName}=${address}\n`;
          console.log(`✅ ${envVarName}: ${address}`);
          foundContracts++;
        }
      } catch (error) {
        console.error(`⚠️  Failed to read ${filename}: ${error.message}`);
      }
    } else {
      console.log(`⏭️  Skipping ${envVarName} (not deployed)`);
    }
  }

  // Write .env.local file
  const envPath = path.join(__dirname, '../.env.local');
  fs.writeFileSync(envPath, envContent);

  console.log(`\n✨ Successfully configured ${foundContracts} contract addresses`);
  console.log(`📝 Environment file written to: ${envPath}`);
  console.log('\n🚀 You can now run: npm run dev');
}

setupEnv().catch((error) => {
  console.error('❌ Setup failed:', error);
  process.exit(1);
});
